default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci

    # Match
    match(type: "appstore", readonly: true)

    # Build
    build_ios_app(
      workspace: "ios/TermVault.xcworkspace",
      scheme: "TermVault",
      clean: true,
      output_directory: "./build"
    )

    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )

    # Notify
    slack(
      message: "New iOS build uploaded to TestFlight!",
      success: true
    )
  end

  desc "Push a new release to App Store"
  lane :release do
    setup_ci

    # Match
    match(type: "appstore", readonly: true)

    # Build
    build_ios_app(
      workspace: "ios/TermVault.xcworkspace",
      scheme: "TermVault",
      clean: true,
      output_directory: "./build"
    )

    # Upload to App Store
    upload_to_app_store(
      force: true,
      skip_screenshots: true,
      skip_metadata: false
    )

    # Notify
    slack(
      message: "New iOS version released to App Store!",
      success: true
    )
  end

  error do |lane, exception|
    slack(
      message: "Error in lane: #{lane}",
      success: false,
      payload: {
        "Error" => exception.message
      }
    )
  end
end
